### ISSUE TITLE
Youtube fullscreen broken

### ISSUE THREAD

**Issue by pimpa76** [nilshellerhoff/widescreen-browsing#9]
When i switch to youtube fullscreen, its just grey. The addon is the problem, if i remove working fine.

**Comment by nilshellerhoff** [comment]
I can indeed confirm this is the case. Unfortunately as mentioned in the description, depending on the CSS of the page, the addon doesn't work on all websites.

I might be able to add a function which disables the custom width when a website changes to fullscreen.

**Comment by nilshellerhoff** [comment]
Should now be fixed by [c11e6d4](https://github.com/nilshellerhoff/widescreen-browsing/commit/c11e6d46fdd532051056bf0aae24f7b1aefe0a4c). When a page switches to fullscreen mode, the original CSS is now restored.

It'll take some days before the update is through Chrome and Firefox webstore approval process.
